# 03 — Data Cleaning

In [1]:
from pathlib import Path
import sys, pandas as pd
ROOT=Path.cwd().parent
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
DATA=ROOT/'data'/'uploads'/'sample_business_data.csv'
df=pd.read_csv(DATA)
df.head()

from src.analysis.core import clean
clean_df=clean(df,drop_duplicates=True,clip_outliers=False)
clean_df.to_parquet(ROOT/'artifacts'/'cleaned_data.parquet',index=False)
clean_df.head()

   customer_id  age  income region  visits  satisfaction  purchased
0            1   58   47184  North       9           2.0          0
1            2   65   44868  North      19           2.7          0
2            3   23   75314  South      17           3.4          1
3            4   63  127974  South      15           3.4          1
4            5   66   59853   West      11           2.1          0

In [2]:
print("Original shape:", df.shape)
print("Cleaned shape:", clean_df.shape)
print("Missing values:", clean_df.isna().sum().sum())
print("Duplicate rows:", clean_df.duplicated().sum())
print("Saved file exists:", (ROOT / "artifacts" / "cleaned_data.parquet").exists())

clean_df.head()

Original shape: (500, 7)
Cleaned shape: (500, 7)
Missing values: 0
Duplicate rows: 0
Saved file exists: True

   customer_id  age  income region  visits  satisfaction  purchased
0            1   58   47184  North       9           2.0          0
1            2   65   44868  North      19           2.7          0
2            3   23   75314  South      17           3.4          1
3            4   63  127974  South      15           3.4          1
4            5   66   59853   West      11           2.1          0